apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pytorch-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-pytorch-app
  template:
    metadata:
      labels:
        app: my-pytorch-app
    spec:
      containers:
        - name: my-pytorch-app
          image: myusername/my-pytorch-app:latest
          ports:
            - containerPort: 80
